usb_camera_driver:
    ros__parameters:
      camera_calibration_file: file:///home/sharedata/Projects/rviz_rqt_investigation/test_ws/src/ros2_usb_camera/config/camera.yaml
      camera_id: 0
      fps: 30.0
      image_width: 320
      image_height: 240
      frame_id: camera_frame
